version: '3.8'  # Make sure we're using a recent version

services:
  postgres-init:
    image: postgres:latest
    environment:
      PGPASSWORD: secure_password_123
    command: >
      psql -h postgres -U bank_user -d bank_recommendations -f /init.sql
    volumes:
      - ./init.sql:/init.sql
    networks:
      - bank_network

  ml-server:
    build:
      context: ./ml-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bank_user:secure_password_123@postgres:5432/bank_recommendations
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./ml-server:/app
    networks:
      - bank_network

  usage-tracker:
    build:
      context: ./usage-tracker
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://bank_user:secure_password_123@postgres:5432/bank_recommendations
    volumes:
      - ./usage-tracker:/app
    networks:
      - bank_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    networks:
      - bank_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db-ui:
    image: dpage/pgadmin4:9.1.0
    restart: always
    ports:
      - 5050:80
    environment:
      DATABASE_URL: postgresql://bank_user:secure_password_123@postgres:5432/bank_recommendations
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./test/db/servers.json:/pgadmin4/servers.json
    networks:
      - bank_network
  
  simulation:
    build:
      context: ./simulation
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - bank_network
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - ./simulation:/app
networks:
  bank_network:
    external: true