version: '3.8'  # Make sure we're using a recent version

services:

  ml-server:
    image: your-acr.azurecr.io/ml-server:latest
    build:
      context: ./ml-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./ml-server/.env

  usage-tracker:
    image: your-acr.azurecr.io/usage-tracker:latest
    build:
      context: ./usage-tracker
      dockerfile: Dockerfile
    env_file:
      - ./usage-tracker/.env

  frontend:
    image: your-acr.azurecr.io/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  simulation:
    image: your-acr.azurecr.io/simulation:latest
    build:
      context: ./simulation
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://bank_user:your_secure_password_here@postgres:5432/bank_recommendations
